name: manually trigger

on: 
    # defining workflow call
    workflow_call: 
        inputs:

            # required = false make its optional.
            username:
                description: 'this is a decription'
                default: 'farm-guy'
                required: false
                type: string
        
        secrets:
            FIRST_NAME:
                required: true
            LAST_NAME:
                required: true

    # defining dispatch for manually trigger
    workflow_dispatch: 
        inputs:

            # required = false make its optional
            username:
                description: 'this is a discription'
                default: 'farm-guy'
                required: false
                type: string

jobs:
    print-username:
        runs-on: windows-latest

        steps:
        - name: print the input name to STDOUT
          run: |
            echo username is ${{ inputs.username }}

        - name: using secret tokens
          run: echo username is ${{ secrets.FIRST_NAME }} ${{ secrets.LAST_NAME }}
