name: automatically trigger

# to run workflow manually
# on: 
#     workflow_dispatch: 

# to trigger workflow automatically
on:
    push: 
        branches: 
            - main

jobs:
    call-publish-workflow:
        # path to workflow defination yaml.
        uses: ./.github/workflows/publish.yaml

        # Optional because required = false in publish.yaml
        with:
            username: 'the-farm-guy'
            
        secrets: 
            FIRST_NAME: ${{ secrets.FIRST_NAME }}
            LAST_NAME: ${{ secrets.LAST_NAME }}
