name: call publish workflow

# on: 
#     workflow_dispatch: 

on:
    push: 
        branches: 
            - main

jobs:
    call-publish-workflow:
        uses: ./.github/workflows/publish.yaml
        with:
            username: 'the-farm-guy'
